[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-server-bing-webmaster"
authors = [
  { name = "Isiah Wheeler", email = "github@isiahwheeler.com" },
]
description = "MCP server for direct Bing Webmaster Tools API access with OData compatibility"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
keywords = ["mcp", "bing", "webmaster", "seo", "api", "odata"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Internet :: WWW/HTTP",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "mcp[cli]>=1.10.0",
    "httpx>=0.28.0",
    "python-dotenv>=1.0.0",
]

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "pytest-asyncio",
    "ruff",
]

[project.urls]
"Homepage" = "https://github.com/isiahw1/mcp-server-bing-webmaster"
"Bug Tracker" = "https://github.com/isiahw1/mcp-server-bing-webmaster/issues"
"Documentation" = "https://github.com/isiahw1/mcp-server-bing-webmaster#readme"

[tool.hatch.build.targets.wheel]
packages = ["mcp_server_bwt"]

[tool.hatch.version]
path = "mcp_server_bwt/version.py"

[project.scripts]
mcp-server-bing-webmaster = "mcp_server_bwt.main:app"

[tool.pytest.ini_options]
pythonpath = "mcp_server_bwt"
asyncio_mode = "auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
exclude = [
    ".+test_"
]

[tool.ruff]
target-version = "py310"
line-length = 100
select = ["E", "F", "I", "N", "W"]
ignore = ["E501"]  # Line too long

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
